ALTER TABLE notifications
  ADD COLUMN IF NOT EXISTS location VARCHAR(255) DEFAULT NULL AFTER meeting_time,
  ADD COLUMN IF NOT EXISTS virtual_link VARCHAR(500) DEFAULT NULL AFTER location,
  ADD COLUMN IF NOT EXISTS agenda TEXT DEFAULT NULL AFTER message,
  ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT 'media' AFTER target_role,
  ADD COLUMN IF NOT EXISTS category VARCHAR(50) DEFAULT 'general' AFTER priority,
  ADD COLUMN IF NOT EXISTS pinned TINYINT(1) DEFAULT 0 AFTER status;
