ALTER TABLE notifications
  ADD COLUMN location VARCHAR(255) DEFAULT NULL,
  ADD COLUMN virtual_link VARCHAR(500) DEFAULT NULL,
  ADD COLUMN agenda TEXT DEFAULT NULL,
  ADD COLUMN priority VARCHAR(20) DEFAULT 'media',
  ADD COLUMN category VARCHAR(50) DEFAULT 'general',
  ADD COLUMN pinned BOOLEAN DEFAULT false;
