export const peruvianOccupations = [
  "Abogado/a",
  "Administrador/a de Empresas",
  "Agente de Seguros",
  "Agrónomo/a",
  "Albañil",
  "Almacenero/a",
  "Animador/a Cultural",
  "Antropólogo/a",
  "Arqueólogo/a",
  "Arquitecto/a",
  "Artesano/a",
  "Asistente Administrativo/a",
  "Asistente Contable",
  "Asistente de Enfermería",
  "Asistente Social",
  "Auditor/a",
  "Bacteriólogo/a",
  "Barbero/a",
  "Barman/Barwoman",
  "Bibliotecario/a",
  "Bioanalista",
  "Biólogo/a",
  "Biomédico/a",
  "Camarero/a",
  "Carpintero/a",
  "Cartero/a",
  "Casero/a",
  "Chef/Cocinero/a",
  "Chófer",
  "Cirujano/a",
  "Comerciante",
  "Comerciante ambulante",
  "Comentarista Deportivo",
  "Conductor de Taxi",
  "Conductor de Uber/Cabify",
  "Conferencista",
  "Consejero/a Educacional",
  "Contador/a",
  "Contratista de Obras",
  "Coordinador/a",
  "Corrector/a de Estilo",
  "Cosmetólogo/a",
  "Cronista",
  "Danza Tradicional",
  "Décorador/a",
  "Defensor/a del Pueblo",
  "Delineante",
  "Dentista/Odontólogo/a",
  "Dermatólogo/a",
  "Desarrollador/a de Software",
  "Dibujante",
  "Director/a de Colegio",
  "Director/a de Empresa",
  "Director/a de Radio",
  "Doctor/a Médico/a",
  "Economista",
  "Editor/a",
  "Educador/a",
  "Electricista",
  "Electrónico/a",
  "Embaucador",
  "Emprendedor/a",
  "Enfermero/a",
  "Enólogo/a",
  "Entrenador/a Deportivo/a",
  "Envase y Empaquetado",
  "Epidemiólogo/a",
  "Escritor/a",
  "Estilista",
  "Estudiante",
  "Farmacéutico/a",
  "Fiscal",
  "Físico/a",
  "Fotógrafo/a",
  "Fonoaudiólogo/a",
  "Funcionario/a Público/a",
  "Geógrafo/a",
  "Geólogo/a",
  "Gerente General",
  "Gerente de Ventas",
  "Guía de Turismo",
  "Historiador/a",
  "Hidráulico/a",
  "Hotelero/a",
  "Impresor/a",
  "Ingeniero/a Ambiental",
  "Ingeniero/a Agrónomo",
  "Ingeniero/a Civil",
  "Ingeniero/a de Minas",
  "Ingeniero/a de Sistemas",
  "Ingeniero/a Electrónico",
  "Ingeniero/a Electromecánico",
  "Ingeniero/a Industrial",
  "Ingeniero/a Mecánico",
  "Ingeniero/a Metalúrgico",
  "Ingeniero/a Químico",
  "Ingeniero/a Sanitario",
  "Ingeniero/a Textil",
  "Investigador/a",
  "Jardinero/a",
  "Jefe de Almacén",
  "Jefe de Compras",
  "Jefe de Personal",
  "Juez",
  "Laboratorista",
  "Libre de ocupación",
  "Locutor/a de Radio/TV",
  "Logística",
  "Maestro/a de Ceremonias",
  "Maestro/a de Obras",
  "Maestro/a / Profesor/a",
  "Manicurista",
  "Mecánico/a",
  "Médico/a Cirujano/a",
  "Médico/a General",
  "Médico/a Pediatra",
  "Músico/a",
  "Naviero/a",
  "Notario/a",
  "Nutricionista",
  "Odontólogo/a",
  "Oficinista",
  "Obrero/a",
  "Oftalmólogo/a",
  "Opticiano/a",
  "Operador/a de Máquina",
  "Operador/a de Radio",
  "Orientador/a",
  "Osteópata",
  "Panadero/a",
  "Paramédico/a",
  "Peluquero/a",
  "Peluquero/a Canino",
  "Pensionista",
  "Perito/a",
  "Periodista",
  "Pintor/a",
  "Policía Nacional",
  "Politólogo/a",
  "Presidente/a del Jurado",
  "Presidente/a Municipal",
  "Productor/a Audiovisual",
  "Productor/a de TV",
  "Profesor/a de Educación Física",
  "Profesor/a de Inglés",
  "Profesor/a de Matemática",
  "Profesor/a de Música",
  "Profesor/a de Religión",
  "Profesor/a Universitario/a",
  "Psicólogo/a",
  "Psicopedagogo/a",
  "Publicista",
  "Químico/a Farmacéutico/a",
  "Radólogo/a",
  "Recursos Humanos",
  "Representante de Ventas",
  "Repartidor/a",
  "Recepcionista",
  "Relaciones Públicas",
  "Religioso/a",
  "Reportero/a",
  "Residente de Obra",
  "Responsable de Calidad",
  "Responsable de Seguridad",
  "Sacerdote/a",
  "Saludista",
  "Secretario/a General",
  "Secretario/a Ejecutivo/a",
  "Seguridad / Vigilante",
  "Sicólogo/a",
  "Soldador",
  "Soplador / A",
  "Sastre / Sastra",
  "Técnico/a Agrícola",
  "Técnico/a Contable",
  "Técnico/a de Enfermería",
  "Técnico/a de Laboratorio",
  "Técnico/a de Minas",
  "Técnico/a de Radiología",
  "Técnico/a Electricista",
  "Técnico/a en Computación",
  "Técnico/a en Electricidad",
  "Técnico/a en Enfermería",
  "Técnico/a en Instalaciones Eléctricas",
  "Técnico/a en Mantenimiento",
  "Técnico/a en Recursos Humanos",
  "Técnico/a Mecánico",
  "Técnico/a Químico",
  "Técnico/a Superior de Enfermería",
  "Tecnólogo/a Médico",
  "Telecomunicaciones",
  "Telefonista",
  "Teólogo/a",
  "Topógrafo/a",
  "Traceador/a",
  "Traductor/a / Intérprete",
  "Trabajador/a Social",
  "Trabajador/a de Banca",
  "Trabajador/a Doméstico/a",
  "Transportista",
  "Trafico de Animales",
  "Tutor/a",
  "Vendedor/a Ambulante",
  "Vendedor/a en tienda",
  "Veterinario/a",
  "Vicerrector/a",
  "Vigilante/a de Seguridad",
  "Webmaster",
  "Youtuber / Influencer",
  "Zootecnista",
]
